name: TravelTales CI PIPELINE

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Revisión del repositorio
        uses: actions/checkout@v4
  
      - name: Configuración de Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
  
      - name: Instalar dependencias
        run: npm install
        working-directory: TravelTales

      - name: Run Unit Tests
        run: npm test -- --coverage
        working-directory: TravelTales
    
  
